### ISSUE TITLE
Nuget package doesn't provide .NET 4.0 version of EasyConsole.

### ISSUE THREAD

**Issue by gdziadkiewicz** [splttingatms/EasyConsole#3]
I would like to use EasyConsole in my .NET 4.0 project. Due to fact that the Nuget package does not contain dll for .NET 4.0 I'm forced to compile EasyConsole from source and manually add the dll to my project. Can you add .NET 4.0 version to the Nuget package? You can find instructions on how to do that here: https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks .

**Comment by damianh** [comment]
.net4.0 is no longer supported, so 👎 from me.
